- src/componenets/common/InputForm/InputForm.style.ts
- src/componenets/common/InputForm/InputForm.tsx
- src/pages/RegisterPage/RegisterPage.style.ts
- src/pages/RegisterPage/RegisterPage.tsx
- 작업 내용 1: InputForm 공통 컴포넌트를 구현했습니다.
- 매개변수
- wrapperWidth: 겉 껍데기의 width -> `string` => `optional`
- labelText: label의 text값 -> `string`
- labelId: input과 연결시키기 위한 id -> `string`
- inputType: input태그의 type -> `'date' | 'file' | 'number' | 'search' | 'tel' | 'text' | 'time'`
- 그 외에 input에 들어갈 내용을 커스터마이징 할 수 있도록 ...props를 넣었습니다!
```
const InputFormStyled = styled(InputForm)`
// 어쩌구 저쩌구
`
```
`<InputForm value={value} onChange={handleChange} ref={inputRef} />`
- style 부분에 더 최소화할 수 있는 점이 있는지 봐주시면 감사하겠습니다.
> feat: InputForm 컴포넌트 구현

- src/constants/storageKeys.ts
- src/utils/localStorage.ts
- 로컬 스토리지 키값 상수 저장
- 로컬 스토리지 관련 함수 추가 (getStorage,setStorage,deleteStorage)
getStorage가 storage를 얻는다? 라는 느낌을 줄 수도 있을것 같아서 getFromStorage같은 변수명으로 바꿀까 고민중임다
> Skrf 146 local storage

- src/components/common/Header/Header.style.ts
- src/components/common/Header/Header.tsx
- src/components/common/SpaceClubHomeLogo/SpaceClubHomeLogo.style.ts
- src/styles/Theme.ts
- 헤더 레이아웃 공통 컴포넌트를 구현했습니다. 
- 사용할 때는 헤더에 포함해줄 요소들을 `<Header></Header>`로 묶어주시면 됩니다. 
수정 전
수정 후
- 빨간 테두리: 헤더 레이아웃입니다. 
- 까만 테두리: 헤더 영역입니다. children들이 들어오게 되는 곳!
- 많은 피드백 환영합니다. 감사합니다!
> SKRF-142 design: 헤더 레이아웃 공통 컴포넌트 구현

- src/constants/api.ts
- src/constants/event.ts
- src/hooks/query/event/useCancelEventMutation.ts
- src/mocks/data/eventData.ts
- src/pages/Layout/SideNav.tsx
- src/pages/ProfilePage/AppliedEvents.tsx
- src/types/api/cancelEvent.ts
- src/types/event.ts
- cancelled => canceled로 오타 잡았습니다 cancelled는 영국식 영어더군요...ㅋㅋ
- eventStatus => apillicationStatus : api명세에서 바뀐 변수명 적용했습니다
- 취소 신청 테스트까지 완료했습니다!
- 취소확정 => 취소완료 : 태그 메시지 변경했습니다! 취소완료가 더 어울릴 것 같아서?
> SKRF-268 fix : 내가 신청한 행사 조회 api 변수명 동기화

- src/hooks/query/auth/useOauthLogin.ts
- src/hooks/query/user/usePostUser.ts
- src/pages/club/InvitePage/InvitePage.tsx
- 클럽 가입시 리턴페이지 정보를 세션스토리지에 저장하고 있었는데, 로그인을 하면서 카카오 화면으로 넘어가게 되니까 세션에 있는 정보가 싹 날아가더라고요. 그래서 로컬에 저장해보도록 하겠습니다.
> SKRF-278 fix: 리턴페이지 정보 localStorage에 저장

- src/components/ScheduleManage/ScheduleManage.tsx
- src/hooks/query/event/useClubSchedulesQuery.ts
- 클럽 일정을 불러올 때 staleTime으로 인해 클럽에 따른 일정이 불러와지지 않는 문제를 해결했습니다. 
- 같은 queryKey에 캐싱된 데이터가 유효하면 staleTime 동안에는 새로운 데이터 요청을 보내지 않는다고 하네요. 근데 clubId는 달라지는데, 그럼 무효한 데이터가 되지 않나..? 이 부분에 대해서는 더 찾아보고 개발일지에 남기도록 하겠습니다.
> SKRF-287 fix: 클럽 바뀔 때마다 클럽일정 api 호출

- src/apis/club/getClubEvents.ts
- src/apis/event/getAllEvents.ts
- src/apis/event/getSearchResult.ts
- src/apis/event/getSubmittedForms.ts
- src/components/SearchInputForm/SearchInputForm.style.ts
- src/components/SearchInputForm/SearchInputForm.tsx
- src/components/SearchResult/SearchResult.style.ts
- src/components/SearchResult/SearchResult.tsx
- src/components/common/EventCard/EventCard.tsx
- src/constants/api.ts
- src/constants/path.ts
- src/hooks/query/club/useClubEventsQuery.ts
- src/hooks/query/event/useAllEventsQuery.ts
- src/hooks/query/event/useSearchResultQuery.ts
- src/hooks/useDebounce.ts
- src/mocks/data/eventData.ts
- src/pages/MainPage/MainPage.tsx
- src/pages/SearchResultPage/SearchResultPage.style.ts
- src/pages/SearchResultPage/SearchResultPage.tsx
- src/pages/club/ClubEventPage/ClubEventPage.tsx
- src/routes/router.tsx
- src/types/api/allEvents.ts
- src/types/api/searchResult.ts
- src/types/club.ts
- src/types/event.ts
- src/types/form.ts
- 검색 api 연결 및 테스트 완료했습니다. 
- 검색창에 검색어를 입력하면 자동완성 결과가 검색창 아래 나타납니다. (검색결과가 18개가 넘을 경우 검색결과 페이지로 이동하는 버튼 보임)
- 검색어 입력 후 돋보기 버튼을 클릭하거나 엔터를 입력하면 검색결과 페이지로 이동합니다. 
아 원래 gif로 만들어서 올리려고 했는데 더미데이터 싹 사라져서 보여드릴 수가 없네요;; 
- 검색창 아래로 내려오는 wrapper의 높이가 고정인 이유는... 그렇게 하지 않으면 검색창 위치가 이상해지기 때문입니다. 네이버처럼 검색창 아래에 딱 붙어서 내려오게 하고 싶은데, 어떻게 하는지 모르겠습니다! 
- 최근 검색어는 당장에 필요한 건 아닐 것 같아서 추후에... 하도록 하겠습니다.
> SKRF-319 feat: 검색 기능, 검색페이지 구현

- src/constants/api.ts
- src/hooks/query/event/useCancelEventMutation.ts
- src/mocks/data/eventData.ts
- src/mocks/event.ts
- src/pages/ProfilePage/AppliedEvents.tsx
- src/types/api/cancelEvent.ts
- src/types/api/getAppliedEvent.ts
- [ResponseBody 변경]
행사 신청 취소 (applicationStatus -> participationStatus)
유저가 신청한 모든 행사 조회  (status-> participationStatus)
- [API Endpoint 변경]
applications -> participate
- 모킹 데이터 삭제
> SKRF-344 fix : 행사 신청 취소 API 스펙 변경

- src/components/ClubHeader/ClubHeader.tsx
- src/constants/tab.ts
- src/pages/club/ClubEventPage/ClubEventPage.tsx
- src/pages/club/ClubHomePage/ClubHomePage.style.ts
- src/pages/club/ClubHomePage/ClubHomePage.tsx
- src/pages/club/ClubManagePage/ClubManagePage.tsx
- src/styles/common.ts
- [ClubHeader 컴포넌트 추가](https://github.com/Space-Club/Frontend/commit/b8bc14390499b1d4e286acc3b8143be85f0fcca1)
- [tabWrapper 스타일 공통으로 분리](https://github.com/Space-Club/Frontend/commit/996c28ecea388fa9b307a83b2040cfc632b2767f)
- [멤버, 관리자 탭 아이템 상수 분리](https://github.com/Space-Club/Frontend/commit/211908a242c2ab639015aaf69958e0e954f371e8)
- [ClubHeader 각 페이지에 적용](https://github.com/Space-Club/Frontend/commit/03e3a731789ddc5158de7fab21d7613fb438ef97)
> SKRF-343 feat : 클럽 역할 별 헤더 아이템 변경

- src/components/FormItem/FormRadio.style.ts
- 작업 내용 1: formItem radio type이 2줄일 경우에 대한 예외처리를 했습니다.
- 없습니다.
> SKRF-332 fix: formRadio 2줄일 경우에 대한 css 추가

- src/components/common/EventCard/EventCard.style.ts
- src/constants/api.ts
- src/pages/MainPage/MainPage.style.ts
- src/pages/MainPage/MainPage.tsx
- src/pages/SearchResultPage/SearchResultPage.style.ts
- src/pages/SearchResultPage/SearchResultPage.tsx
- src/pages/club/ClubEventPage/ClubEventPage.style.ts
- src/pages/club/ClubEventPage/ClubEventPage.tsx
- src/styles/common.ts
- 메인페이지, 클럽행사 페이지, 검색결과 페이지의 행사들 정렬 레이아웃을 grid로 수정했습니다. 이때 한 줄에 최대 3개만 보이도록 설정했습니다. 포스터 옆에 행사 정보도 적혀 있어서, 한 줄에 여러 개의 행사들이 들어가게 되니 산만해 보였기 때문입니다!
- 각 행사들은 한 페이지에 최대 12개씩 보여집니다. 12개인 이유는... 페이지가 2 이상이라면 화면을 좁혔을 때 grid의 칸이 비는 것이 어색해 보이기 때문입니다. 한 줄에 최대 3개씩 들어가므로 12개라면 그리드가 깨지지 않습니다!
> SKRF-369 design: 행사들 레이아웃 수정

- src/components/SearchInputForm/SearchInputForm.tsx
- src/hooks/query/event/useSearchResultQuery.ts
- src/pages/SearchResultPage/SearchResultPage.style.ts
- src/pages/SearchResultPage/SearchResultPage.tsx
- 검색결과 없을 때 알려주기: SKRF-390번이 머지되면 검색결과 페이지에서 '검색결과가 없습니다' 스타일을 common 스타일로 적용시켜줄 예정입니다. 
- input focus 시 검색결과 띄워주기
- 검색 validation 추가: 빈값, 공백문자 입력 후 검색 버튼 클릭 or 엔터키 입력 시 작동x
- 검색결과 페이지 페이지네이션 컴포넌트 위치 하단으로 조정 및 query키 수정
> SKRF-393 fix: search page n component

- src/components/common/EventCard/EventCard.style.ts
- src/components/common/EventCard/EventCard.tsx
- src/constants/api.ts
- src/pages/club/ClubEventPage/ClubEventPage.style.ts
- src/pages/club/ClubEventPage/ClubEventPage.tsx
- src/styles/common.ts
- 클럽 행사 비어 있을 때 메시지 중앙처리하기
- 클럽 행사 페이지네이션 하단에 위치하게 하기
- 이벤트카드 제목 두 줄 이상 ellipsis처리
- 이벤트 카드 장소와 클럽 명 사이 공간 주기
- 마감일 있는 경우 ‘마감: 날짜’로 보여주기
- 클럽 행사 정렬 수정하기
> SKRF-390 fix: club events page

- src/components/ClassificationCard/ClassificationCard.style.ts
- src/components/ImageForm/ImageForm.style.ts
- src/components/common/InputForm/InputForm.style.ts
- src/components/common/InputForm/InputForm.tsx
- src/constants/errorMessage.ts
- src/pages/event/WriteEventInfoPage/PerformanceForm/PerformanceForm.tsx
- src/pages/event/WriteEventInfoPage/PromotionForm/PromotionForm.tsx
- src/pages/event/WriteEventInfoPage/RecruitForm/RecruitForm.tsx
- src/pages/event/WriteEventInfoPage/ScheduleForm/ScheduleForm.tsx
- src/utils/dataTransform.ts
- src/utils/validate.ts
- 작업 내용 1: 공연 종류 선택시 선택카드가 커지는 비율을 조정했습니다.
- 작업 내용 2: input에서 마이너스로 값이 바뀌지 않도록 했습니다.
- 작업 내용 3: input type이 number일 경우, 화살표가 보이지 않도록 변경했습니다.
- 작업 내용 4: input type이 number일 경우, 각 input의 단위를 추가했습니다.
- 작업 내용 5: input type이 text일 경우, 공백에 대한 validation을 추가했습니다.
- 작업 내용 6: 포스터 이미지의 속성을 cover로 변경했습니다.
- 작업 내용 7: 공연 내용 제출 시, 앞 뒤에 공백을 제거 후 제출되도록 했습니다.
- 작업 내용 8: 각 정보들이 없을 시, null로 제출되도록 했습니다.
- 없습니다.
- input type이 datetime-local일 경우, 키보드로 일정이 입력되는 것을 막지 못했는데 방법이 있을까요?
- input type이 datetime-local일 경우, time이 무한 스크롤 되는 것을 막을 방법이 있을까요?
> SKRF-417 fix: 행사정보작성페이지 QA

- src/apis/interceptor.ts
- src/components/ApplyCancelButton/ApplyCancelButton.style.ts
- src/components/ApplyCancelButton/ApplyCancelButton.tsx
- src/components/ChangeFormStatusButton/ChangeFormStatusButton.style.ts
- src/components/ChangeFormStatusButton/ChangeFormStatusButton.tsx
- src/components/Modals/FormDetailModal/FormDetailModal.style.ts
- src/components/Modals/FormDetailModal/FormDetailModal.tsx
- src/components/SubmittedForms/Category/Category.style.ts
- src/components/SubmittedForms/Category/Category.tsx
- src/components/SubmittedForms/FormStatus/FormStatus.style.ts
- src/components/SubmittedForms/FormStatus/FormStatus.tsx
- src/components/SubmittedForms/SubmittedForm/SubmittedForm.style.ts
- src/components/SubmittedForms/SubmittedForm/SubmittedForm.tsx
- src/components/SubmittedForms/SubmittedForms.style.ts
- src/components/SubmittedForms/SubmittedForms.tsx
- src/hooks/query/form/useSubmittedFormStatusMutation.ts
- src/pages/event/SubmittedFormsPage/SubmittedFormsPage.style.ts
- src/types/forms.ts
- 제출된 폼 상세보기 커서포인터로 바꾸기
- 상태 선택 시 버튼이나 원클릭 요소(체크박스)로 바꾸기
- 페이지네이션 하에 두기
- 취소처리 되었으면 ‘취소완료’로 바꾸기
- 제출된 폼 상세보기에 타이틀 달아주기: 제출된 시각으로
- 제출된 폼에 제출시간 넣어주기
리뷰 반영 후
> SKRF-391 fix: 제출된 폼 페이지 QA 반영

- src/components/UserApplyButton/UserApplyButton.tsx
- src/constants/event.ts
- src/pages/event/EventDetailPage/EventDetailPage.style.ts
- src/types/api/getEventDetail.ts
- 작업 내용 1: 아래의 4가지 경우에 대해 신청을 막는 기능을 구현했습니다.
1. 모집인원이 다 찼을 경우
2. 폼 신청 기간이 지났을 경우
3. 공연 기간이 지난 경우
4. 이미 공연을 신청한 경우
- 상세페이지에 들어갔을 때의 지원자 수 기준으로 인원이 다 찼는지 여부를 검사하고 있는데,
신청이 되는 순간은 폼 작성을 끝마치고 버튼을 누른 순간이므로 그 사이에 여러 명이 신청할 경우가 있습니다.
이 경우에는 백엔드의 에러메시지를 보고 그에 따라서, 신청이 마감되었다고 보여주는 기능의 추가 구현이 필요할 것 같습니다.
- 모집공고의 경우에는 뽑는 인원과 신청은 계속 받을 수 있다고 생각하는데, 이에 대해 어떻게 생각하시나요?
> SKRF-330 feat: 신청 막는 기능 구현

- src/hooks/useCarousel.ts
- 첫 공지사항을 작성할 때 캐러샐이 0/1로 표기되는 오류를 수정했습니다
> SKRF-423 fix : 캐러샐 currentIndex항상 범위 내에 존재하게 수정

- src/components/ClubEvents/ClubEvent.style.ts
- src/components/ClubEvents/ClubEvents.tsx
- src/components/MainEvents.tsx
- src/components/MainEvents/MainEvents.tsx
- src/components/SearchedEvents.tsx
- src/components/common/Spinner/Spinner.style.ts
- src/hooks/query/club/useClubEventsQuery.ts
- src/hooks/query/club/useGetClubQuery.ts
- src/hooks/query/event/useAllEventsQuery.ts
- src/hooks/query/event/useSearchResultQuery.ts
- src/pages/MainPage/MainPage.tsx
- src/pages/SearchResultPage/SearchResultPage.tsx
- src/pages/club/ClubEventPage/ClubEventPage.style.ts
- src/pages/club/ClubEventPage/ClubEventPage.tsx
- src/pages/club/ClubManagePage/ClubManagePage.tsx
- 메인페이지, 클럽행사페이지, 검색결과페이지의 events들을 컴포넌트로 분리하였습니다.
- 메인페이지, 클럽행사페이지, 검색결과페이지, 클럽폼페이지, 클럽관리페이지에 suspense를 적용하였습니다. 
- 적용하지 않은 페이지의 경우 쿼리 훅을 사용하는 컴포넌트로 분리되지 않아 suspense 처리를 할 수 없기 때문입니다! suspense 처리가 필요할 경우 담당한 페이지에서 컴포넌트로 만들고 추가하시면 되겠습니다.
- 이제 진짜 안 날 겁니다..오류.......
> SKRF-379 fix: 서스펜스 오류 해결

- src/components/common/Breadcrumb/Breadcrumb.tsx
- src/constants/path.ts
- src/constants/tab.ts
- src/utils/getBreadcrumb.ts
- 행사 종류가 클럽일정일 때 브레드크럼이 모집공고로 뜨던 문제 해결했습니다.
> SKRF-438 fix: 행사 종류가 클럽일정일 때 브레드크럼이 모집공고로 뜨던 문제 해결

- src/components/ChangeFormStatusButton/ChangeFormStatusButton.style.ts
- src/hooks/query/event/useGetSubmittedFormsQuery.ts
- src/pages/event/SubmittedFormsPage/SubmittedFormsPage.tsx
- 제출된 폼이 없을 경우 안내메시지를 보여줍니다.
- 제출된 폼 query key를 추가했습니다.
- 제출된 폼이 취소상태인 경우 상태변경버튼 cursor:default
> SKRF-433 fix: submitted forms page

- src/components/common/Poster/Poster.tsx
- 포스터이미지 없을 시 아이콘 띄우기를 햇씁니다. 우선 아이콘은 임시입니다.
> SKRF-439 design: 포스터이미지 없을 시 아이콘 띄우기

- src/components/ChangeFormStatusButton/ChangeFormStatusButton.tsx
- src/components/Modals/FormDetailModal/FormDetailModal.tsx
- src/components/SubmittedForms/Category/Category.tsx
- src/components/SubmittedForms/SubmittedForm/SubmittedForm.tsx
- src/components/SubmittedForms/SubmittedForms.tsx
- src/styles/common.ts
- src/types/forms.ts
- 제출된 폼 페이지에서 공연 카테고리일 때 '인원수'를 보여줍니다.
- 상태변경버튼 클릭 시 모달 메시지 "확인"->"승인"
- 취소요청일 때 상태변경 불가능
> SKRF-452 refactor: submitted forms page exception

- src/components/UserApplyButton/UserApplyButton.tsx
- src/components/common/BookMark/BookMark.tsx
- src/pages/event/EventDetailPage/EventDetailPage.style.ts
- src/pages/event/EventDetailPage/EventDetailPage.tsx
- 작업 내용 1: 비로그인시 북마크 기능을 막았습니다.
- 없습니다.
- 없습니다.
> SKRF-461 fix: 비로그인시 북마크 제한

- src/components/common/Poster/Poster.style.ts
- src/components/common/Tab/Tab.style.ts
- 탭, 포스터 텍스트 white-space:nowrap처리
> SKRF-469 design: 탭, 포스터 텍스트 white-space:nowrap처리

- src/components/ManagerButton/ManagerButton.tsx
- src/components/PerformanceForm/PerformanceForm.tsx
- src/components/PromotionForm/PromotionForm.tsx
- src/components/RecruitForm/RecruitForm.tsx
- src/components/ScheduleForm/ScheduleForm.tsx
- src/components/UserApplyButton/UserApplyButton.tsx
- src/hooks/query/event/useIsBookmarkedQuery.ts
- src/hooks/query/event/usePostEventInfoMutation.ts
- src/hooks/useException.ts
- src/pages/event/EventDetailPage/CategoryDetail/CategoryDetailForm.tsx
- src/pages/event/EventDetailPage/EventDetailPage.style.ts
- src/pages/event/EventDetailPage/EventDetailPage.tsx
- src/utils/timeTransform.ts
- src/utils/validate.ts
- 작업 내용 1: 행사 생성 시 행사 내용 maxLength 설정하기
- 작업 내용 2: 정보작성 실패시 toast띄워주기
- 작업 내용 3: 수정할 때 정보작성 폼 validation 무효화하기
- 작업 내용 4: 행사상세페이지 모집공고 지원현황 안 보여주기
- 작업 내용 5: 상페페이지 비로그인시 매니저 여부와 북마크 여부 보내지 않도록 하기
- 작업 내용 6: 상세페이지 행사 내용 content 변경
행사 내용이 밑으로 안 가고 같이 있으면 모양이 이상해지네요ㅠㅡㅠ 밑에 행사 내용 디자인을 어떻게 해야할지 잘 모르겠네요..
> SKRF0470 행사정보작성페이지 QA 3차

- src/hooks/query/event/useCancelEventMutation.ts
- 참여신청한 행사에 대해 취소/취소요청을 보내면 제출된 폼의 queryKey를 무효화합니다.
> SKRF-473 fix: 참여신청한 행사 취소요청 혹은 취소 시 제출된 폼 QUERYKEY무효화

- src/apis/club/deleteClubComment.ts
- src/apis/club/getClubComments.ts
- src/apis/club/postClubComment.ts
- src/components/ClubComment/ClubComment.style.ts
- src/components/ClubComment/ClubComment.tsx
- src/components/ClubComments/ClubComments.style.ts
- src/components/ClubComments/ClubComments.tsx
- src/components/ClubPost/ClubPost.style.ts
- src/components/ClubPostDetail/ClubPostDetail.style.ts
- src/components/ClubPostDetail/ClubPostDetail.tsx
- src/components/ClubPosts/ClubPosts.style.ts
- src/components/WriteClubComment/WriteClubComment.style.ts
- src/components/WriteClubComment/WriteClubComment.tsx
- src/constants/api.ts
- src/hooks/query/club/useClubCommentMutation.ts
- src/hooks/query/club/useDeleteClubCommentMutation.ts
- src/hooks/query/club/useGetClubCommentsQuery.ts
- src/pages/club/ClubPostDetailPage/ClubPostDetailPage.style.ts
- src/pages/club/ClubPostDetailPage/ClubPostDetailPage.tsx
- src/pages/club/ClubPostWritePage/ClubPostWritePage.style.ts
- src/pages/club/ClubPostWritePage/ClubPostWritePage.tsx
- src/types/api/deleteClubComment.ts
- src/types/api/getClubComments.ts
- src/types/api/getClubPost.ts
- src/types/api/postClubComment.ts
- src/utils/getTimeStamp.ts
- 클럽 게시글 생성/삭제 기능을 구현했습니다.
- 백엔드 측에서 임시 데이터를 넣어 놓아서 우선 구현은 아래 사진과 같이 되어 있습니다.
> SKRR-13 feat: 클럽 게시글 댓글 생성/삭제 기능 구현

- src/components/BookmarkedCard/BookmarkedCard.tsx
- src/components/common/AppliedEventCard/AppliedEventCard.tsx
- src/components/common/Poster/Poster.tsx
- src/components/common/Skeleton/ProfileSkeleton.tsx
- src/hooks/useCarousel.ts
- src/hooks/useIsIntersecting.ts
- src/hooks/useLazyImage.ts
- src/pages/ProfilePage/ProfilePage.tsx
- src/routes/router.tsx
useIsIntersection.ts : intersectionApi를 사용해서 타겟이 뷰포트 내에 진입했는지 판단을 도와줍니다.
useLazyImage.ts : useIsIntersection을 사용해서 이미지가 뷰포트 내에 진입했을 때 실제 이미지 src를 반환합니다. 진입 전에는 대체 이미지 src를 반환합니다.
코드 스플리팅이라는 기법인데 왜 이따구로 어려운 단어를 쓰는지 모르겠습니다?
그냥 번들링 과정에서 코드를 하나의 청크로 안 묶고 여러개로 나눠 필요할 때마다 코드 청크를 가져오는 방식입니다.
최초 페이지 로딩 시간을 줄여줍니다.
https://ko.legacy.reactjs.org/docs/code-splitting.html < 참고하면 좋은 자료
별거는 아니고 Spinner위에 헤더 컴포넌트를 추가했습니다.
<hr/>
일단 프로필 페이지에만 적용했습니다.
활용법이 쉬우니 순차적으로 적용하면 좋을 것 같습니다.
이미지 지연 로딩은 Poster 컴포넌트 옵션에 isLazy 하나만 추가하면 됩니다.
스플리팅도 한 줄만 추가하면 됩니다.
다만 스플리팅 할 떄 lazy컴포넌트는 suspense 컴포넌트 하위에서 렌더링되어야 합니다.
그 이유는 React.lazy는 Promise객체를 반환하는 비동기 함수입니다. ( 정확히는 export 모듈을 resolve하는 Promise입니다 )
페이지에 진입하고 필요한 js파일을 가져오는 동안 해당 Promise는 pending상태 입니다.
이 pending상태 동안 페이지를 대체할 fallback이 있어야 하기 때문에 suspense하위에 lazy컴포넌트가 …
> Refactor : 프로필 페이지 내 Poster image에 lazy load 추가 및, 프로필 페이지 코드 청크 분할

- src/apis/club/deleteClubPost.ts
- src/apis/club/putClubPost.ts
- src/components/ClubPost/ClubPost.tsx
- src/components/ClubPostDetail/ClubPostDetail.tsx
- src/constants/api.ts
- src/constants/modalMessage.ts
- src/hooks/query/club/useDeleteClubPostMutation.ts
- src/hooks/query/club/usePostCreateClubPost.ts
- src/hooks/query/club/usePutClubPostMutation.ts
- src/pages/club/ClubBoardPage/ClubBoardPage.style.ts
- src/pages/club/ClubPostWritePage/ClubPostWritePage.style.ts
- src/pages/club/ClubPostWritePage/ClubPostWritePage.tsx
- src/types/api/deleteClubPost.ts
- src/types/api/putClubPost.ts
- 클럽 게시글 삭제 및 수정 기능을 구현했습니다.
- 아직 클럽 게시글 사진 첨부 관련하여 백엔드에서 난 오류가 해결되지 않았습니다.
- 사진이 첨부된 게시글을 수정할 때... 첨부되어 있던 사진 정보를 어떻게 사용자에게 보여줄지 고민 되네요!
> SKRR-28 feat: 클럽 게시글 삭제 및 수정 기능 구현

- src/apis/club/postCreateClubPost.ts
- src/components/ClubComment/ClubComment.style.ts
- src/components/ClubComments/ClubComments.tsx
- src/components/ClubPost/ClubPost.style.ts
- src/components/ClubPost/ClubPost.tsx
- src/components/ClubPostDetail/ClubPostDetail.style.ts
- src/components/ClubPostDetail/ClubPostDetail.tsx
- src/components/WriteClubComment/WriteClubComment.style.ts
- src/components/WriteClubComment/WriteClubComment.tsx
- src/hooks/query/club/useGetClubCommentsQuery.ts
- src/pages/club/ClubBoardPage/ClubBoardPage.style.ts
- src/pages/club/ClubBoardPage/ClubBoardPage.tsx
- src/pages/club/ClubPostDetailPage/ClubPostDetailPage.tsx
- src/pages/club/ClubPostWritePage/ClubPostWritePage.style.ts
- src/pages/club/ClubPostWritePage/ClubPostWritePage.tsx
- src/types/api/getClubComments.ts
- src/types/api/postCreateClubPost.ts
- 댓글 목록 조회 api 변경사항 수정
- 댓글 작성 시 비밀 설정 오류 수정
- 클럽 게시글 수정 시 이전 사진 반영
> SKRR-29 feat: club post etc
