.husky/pre-commit, package-lock.json, package.json
- 작업 내용 1: husky 및 lint-staged 설정
궁금하신 있다면 말씀 부탁드립니다.
=> chore: husky 및 lint-staged 설정

package-lock.json, package.json, src/componenets/common/EventCard/EventCard.style.ts, src/componenets/common/EventCard/EventCard.tsx
- 이벤트 카드 공통 컴포넌트를 구현했습니다. 
- 마우스 호버시 약간 커지는 애니메이션을 적용했습니다. 추후 변경 가능성이 있습니다. 
- 아바타 공통 컴포넌트를 만든 후에 추가할 예정입니다.
=> SKRF-137 design: 이벤트 카드 공통 컴포넌트 구현

package-lock.json, package.json
- react-icons 라이브러리 추가
pull받으시고 npm i 해주세요!
=> SKRF-143 feat : react-icons라이브러리 추가

package-lock.json, src/components/common/VerticalScroll/VerticalScroll.style.ts, src/components/common/VerticalScroll/VerticalScroll.tsx
=> SKRF-144 vertical scroll 공통 컴포넌트 구현

src/components/common/Banner/Banner.style.ts, src/components/common/Banner/Banner.tsx, src/pages/MainPage.tsx
- 배너 컴포넌트를 구현했습니다. 
- width와 height을 지정해줄 수 있습니다.
=> SKRF-139 design banner component

src/components/SearchInputForm/SearchInputForm.style.ts, src/components/SearchInputForm/SearchInputForm.tsx, src/pages/MainPage.tsx, src/styles/Theme.ts
- 메인페이지 UI 구현하는 데에 필요하길래 검색창 UI만 만들어 뒀습니다. 
- 선을 쓰는 부분은 Theme.color.lineColor를 사용하시면 좀 더 예쁩니다! 참고하시길... 살짝 보라색 계열이에요.
=> SKRF-166 design: 메인페이지 검색창 컴포넌트 구현

src/components/ActiveButton/ActiveButton.style.ts, src/components/ActiveButton/ActiveButton.tsx, src/components/common/Avatar/Avatar.style.ts, src/components/common/Avatar/Avatar.tsx, src/constants/club.ts, src/pages/club/CreateClubPage.tsx, src/pages/club/CreateClubPage/CreateClubPage.style.ts, src/pages/club/CreateClubPage/CreateClubPage.tsx, src/routes/index.tsx, src/styles/Theme.ts, src/types/components.ts, src/utils/getFontSize.ts
- 클럽 생성 페이지 디자인을 구현했습니다. 
: inputForm 컴포넌트 머지 전이라 기존 컴포넌트를 갖다 썼습니다. 
: 아바타 컴포넌트는 다시 디자인을 손 봐야할 것 같습니다. 피그마 디자인이 싹 바뀌어서... :)
- ActiveButton 컴포넌트를 구현했습니다. 
: semiActive컬러의 버튼
- 최대한 반응형 친화적(?)으로 구현하고자 하였습니다.
- 클럽 생성하기 버튼 위치가 fixed로 있는 게 디자인 상 자연스럽다고 생각했는데, 아니라면 말씀해주시면 감사하겠습니다! 
- 아바타가 창 크기 줄일 때 사이드바 위로 올라가는데 왜 그럴까요? 현재는 min-width 설정을 해 놓아서 올라갈 일은 없지만 이유가 궁금합니다! 고쳐야 할 것 같아서요. 아바타 컴포넌트 말고 다른 텍스트 요소들은 사이드 바 밑으로 잘 갑니다.
=> SKRF-150 design: CreateClubPage ui 구현

src/apis/axiosClient.ts, src/apis/event/getMyEvent.ts, src/constants/api.ts, src/hooks/query/event/useMyEvent.ts, src/mocks/event.ts, src/mocks/worker.ts, src/types/event.ts
- axiosClientWithAuth 추가 (토큰 사용하는 요청)
- getMyEvent api추가
- useGetMyEvent 커스텀 훅 추가
- msw api 모킹
msw 모킹 테스트 데이터를 분리할까요??
mocks/data,handlers 이런 느낌??
Response, Reqeust에 대한 타입을 다 지정해줬습니다!
이런 방식은 어떤지 의견이 궁금합니다 ^.^
=> SKRF-163 MyEvent api 모킹

src/pages/Layout/SideNav.style.ts, src/styles/common.ts
- 공통 스타일 sideBarScrollStyled 제작
=> SKRF-168 style : 사이드바 스크롤 스타일 적용

vercel.json
- vercel.json파일을 추가하여 새로고침 시 오류를 수정했습니다
=> SKRF-221 feat : vercel 새로고침 오류 수정

package-lock.json, package.json, src/apis/auth/oauthLogin.ts, src/apis/axiosClient.ts, src/apis/users/postUser.ts, src/constants/auth.ts, src/constants/storageKeys.ts, src/hooks/query/auth/useOauthLogin.ts, src/mocks/users.ts, src/pages/RegisterPage/RegisterPage.tsx, src/types/api/authLogin.ts, src/types/api/postUser.ts, src/types/auth.ts
- 카카오 로그인 버튼 클릭 => 
1) res의 token이 빈 스트링일 때 : 첫 가입 유저임, useId 스토리지에 저장 후 register페이지로 이동
2) res의 토큰이 빈 스트링이 아닐 때 : 가입된 유저임, token 스토리지에 저장 후 main페이지로 이동
=> SKRF-219 fix : 로그인 관련 바뀐 API 적용

src/apis/axiosClient.ts, src/apis/users/getMyClub.ts, src/constants/api.ts
- 사이드바에서 클럽 목록을 불러오는 api 테스트 완료했습니다. 
- 아직 로그인 부분이 미완료 상태라 현지님이 주신 임시 테스트 토큰으로 진행했습니다.
=> SKRF-232 feat: 사이드바에서 나의 클럽 목록 불러오기 api 테스트

src/constants/auth.ts
=> Skrf-237 fix : redirect url 변경하기

src/apis/event/postPerformanceForm.ts
- 작업 내용 1: poster 변수명이 posterImage로 변경됨에 따라 수정했습니다.
- 없습니다.
- 없습니다.
=> 행사 폼 신청 API 테스트 및 변수 이름 변경

src/apis/axiosClient.ts, src/apis/club/postCreateClub.ts, src/constants/path.ts, src/hooks/query/club/useClub.ts, src/hooks/query/club/useClubs.tsx
=> SKRF-222 feat: 클럽 생성 시 생성된 클럽으로 이동

.husky/pre-push, src/components/ActiveButton/ActiveButton.style.ts, src/components/common/BigLogo/BigLogo.style.ts, src/components/common/BigLogo/BigLogo.tsx, src/constants/logo.ts, src/pages/LoginPage/LoginPage.style.ts, src/pages/LoginPage/LoginPage.tsx, src/pages/NotFoundPage.tsx, src/pages/NotFoundPage/NotFoundPage.style.ts, src/pages/NotFoundPage/NotFoundPage.tsx, src/routes/router.tsx
- BigLogo 컴포넌트를 만들었습니다. 
- 에러 페이지 만들었습니다.
- 로그인 페이지 레이아웃 변경했습니다. 안 예쁘길래..
=> SKRF-234 feat: 에러페이지 구현

src/apis/event/getMyEvent.ts, src/constants/api.ts
- 내 이벤트 보기 엔드포인트가 명세와 맞지 않아 발생한 오류를 수정했습니다
=> SKRF-204 fix : myEvent 엔드포인트 수정

src/components/ClubNotice/ClubNotice.style.ts, src/components/ClubNotice/ClubNotice.tsx, src/components/Modals/NoticeModal.style.ts, src/components/Modals/NoticeModal.tsx, src/pages/club/ClubHomePage/ClubHomePage.tsx, src/styles/common.ts
- 공지사항 컴포넌트 제작
- 공지사항 모달 컴포넌트 제작
이제 공지사항 CRUD api만 붙히면 됩니다
상황이 많아서 로직이 다소 복잡하네요
삭제할때 confirm을 해야할 것 같은데 이게 모달이다 보니까 또 모달 띄우기가 애매하네요 어쩌면 좋을까요?
=> SKRF-261 feat : 클럽 공지사항, 모달

src/components/common/CarouselSlider/Carousel.style.ts, src/components/common/CarouselSlider/Carousel.tsx, src/hooks/useCarousel.ts
- useCarousel 커스텀 훅 추가
- Carousel 컴포넌트 추가
```tsx
<Carousel itemWidth={30} totalItem={4}>
<div>1</div>
<div>2</div>
<div>3</div>
<div>4</div>
</Carousel>
```
사용법을 쉽게하기 위해 알아서 다해주는 캐러샐 컴포넌트 추가했습니다
오늘의 집과 마켓컬리의 대문짝을 참고했어요
https://ohou.se/
https://www.kurly.com/main
=> SKRF-259 feat : useCarousel 추가

package.json, src/App.tsx, src/assets/fonts/font.css, src/styles/GlobalStyle.ts
- 배포단에서 폰트 오류 수정
- preview 포트 번호 설정
배포단에서 나는 오류 수정했습니다
배포시 오류 확인하고 싶으시면
npm run build
npm run preview 하시면 가능합니다
=> SKRF-262 fix : 배포단에서 폰트 오류 수정

src/components/InviteLink/InviteLink.tsx, src/hooks/query/club/useInviteLinkQuery.ts, src/mocks/data/clubData.ts, src/types/api/postInviteLink.ts
- 작업 내용 1: 초대링크 API response를 변경했습니다.
- 없습니다.
- 없습니다.
=> SKRF-265 fix: 초대링크 API Response 변경

src/apis/event/postEventApply.ts, src/constants/api.ts, src/pages/club/ClubEventPage/ClubEventPage.tsx, src/types/club.ts
행사 참여 신청 시 잘못된 요청 url을 수정했습니다. 
행사 생성 시 clubId가 하드코딩 되어 있던 걸 수정했습니다.
=> fix: 행사 참여 신청 시 요청 url 오류 수정, 행사 생성 시 clubId 설정

src/components/LoginButton/LoginButton.style.ts, src/components/LoginButton/LoginButton.tsx, src/pages/Layout/SideNav.tsx
- 초기에는 로그인 한 유저만 사용할 수 있어서 로그인 버튼이나 로그인 되어 있는지 보여주는 걸 따로 안 만들었는데, 이제 필요하게 되어 만들어봤습니다.
- 로그인하지 않으면 클럽생성 버튼도 보이지 않게 해봤는데 이상한가요?
=> SKRF-269 feat: 로그인 하지 않은 유저일 시 프로필 대신 로그인 버튼 보여줌

src/components/FormCheckOptions/FormCheckOptions.style.ts, src/components/FormCheckOptions/FormCheckOptions.tsx, src/components/Modals/Modal.style.ts, src/components/common/CheckBox/CheckBox.style.ts, src/components/common/CheckBox/CheckBox.tsx, src/constants/modalMessage.ts, src/constants/path.ts, src/pages/club/ClubEventPage/ClubEventPage.tsx, src/pages/event/WriteEventFormPage.tsx, src/routes/router.tsx
- CheckBox 공통 컴포넌트 추가
- alertModal 스타일 수정
- FormCheckOptions 컴포넌트 추가 (CheckBox를 통해 만든 폼 커스텀 페이지의 체크박스 두개)
@colorkite10 AlertModal content가 중앙정렬 되어 있는게 피그마 디자인과 다른 것 같아서 수정했습니다! padding도 조금 수정했는데 괜찮을까요?
=> SKRF-268 feat : 체크박스 컴포넌트 UI구현

src/apis/form/postFormOption.ts, src/components/FormCheckOptions/FormCheckOptions.style.ts, src/components/FormCheckOptions/FormCheckOptions.tsx, src/components/FormInformationEditor/FormInformationEditor.style.ts, src/components/FormInformationEditor/FormInformationEditor.tsx, src/components/FormItem/FormItem.tsx, src/components/FormOption/FormOption.tsx, src/components/FormOptionButton/FormOptionButton.style.ts, src/components/FormOptionButton/FormOptionButton.tsx, src/components/FormOptionDropdown/FormOptionDropdown.tsx, src/components/FormOptions/FormOptions.tsx, src/constants/api.ts, src/constants/errorMessage.ts, src/constants/form.ts, src/constants/modalMessage.ts, src/constants/successMessage.ts, src/context/FormOptionContext.tsx, src/hooks/query/form/usePostFormOptionMutation.ts, src/pages/event/WriteEventFormPage.tsx, src/pages/event/WriteEventFormPage/WriteEventFormPage.style.ts, src/pages/event/WriteEventFormPage/WriteEventFormPage.tsx, src/routes/router.tsx, src/types/api/postFormOption.ts, src/types/event.ts, src/types/form.ts
- [작업 내용 1](https://github.com/Space-Club/Frontend/pull/88)
모르고 요 브랜치에서 추가적인 작업 계속해서 새로 PR올립니다ㅠㅠ
- 내용은 같고 FormOptionContext.ts에 useMemo랑 useCallback만 추가했으니 별도의 리뷰는 안하셔도 무방합니다!
=> SKRF-260 feat : 폼 설정 페이지 api 연결 (깃 커밋 오류 수정)

src/hooks/query/club/useClubMembersQuery.ts, src/hooks/query/club/useGetClubNoticeQuery.ts
- 공지사항, 멤버 쿼리에 clubId를 쿼리 키로 추가하여 clubId가 바뀔 때마다 fetch받도록 수정했어요
=> SKRF-274 feat : 공지사항, 멤버 쿼리 키 추가

src/apis/club/getInviteClubInfo.ts, src/components/InviteClubInfo/InviteClubInfo.style.ts, src/components/InviteClubInfo/InviteClubInfo.tsx, src/components/InviteLink/InviteLink.tsx, src/constants/api.ts, src/constants/successMessage.ts, src/hooks/query/club/useGetInviteClubInfoQuery.ts, src/hooks/query/club/useInviteLinkQuery.ts, src/hooks/query/club/useJoinClub.ts, src/pages/club/InvitePage/InvitePage.style.ts, src/pages/club/InvitePage/InvitePage.tsx
- 초대링크: 클럽 가입하기 페이지 url로 변경
- 가입하기 페이지에서 클럽 정보 불러오지 못하는 오류 해결
- 이 코드가 머지 되어야 초대링크 관련 테스트를 할 수 있을 것 같습니다. 
TODO:
1. 가입x 유저가 링크를 받고 가입할 때 : 로그인 페이지로 이동->추가정보 입력->완료 후 다시 가입 페이지로 돌아오는지 확인->가입도 잘 되는지 확인
2. 가입o 로그인x 유저가 링크를 받고 가입할 때 : 로그인 페이지로 이동->완료 후 다시 가입 페이지로 돌아오는지 확인->가입도 잘 되는지 확인
=> SKRF-272 test: 클럽 가입하기 테스트

src/hooks/query/club/useGetClubQuery.ts
- 왜인지 추가했던 쿼리키가 사라져서 다시 PR올립니다
=> SKRF-277 fix : useGetClubQuery queryKey 추가

src/hooks/query/auth/useOauthLogin.ts, src/hooks/query/user/usePostUser.ts, src/pages/club/InvitePage/InvitePage.tsx
This reverts commit 6c1e4238ac6e07172aab77fc194c87ca64607b93.
- 작업 내용 1
- 작업 내용 2
=> Revert SKRF-278 fix: 리턴페이지 정보 localStorage에 저장

src/constants/errorMessage.ts, src/constants/successMessage.ts, src/hooks/query/club/useClub.ts, src/hooks/query/club/useClubEventsQuery.ts, src/hooks/query/club/useEditClubMutation.ts, src/hooks/query/club/useInviteLinkQuery.ts, src/hooks/query/event/useGetEventBookMarkQuery.ts, src/hooks/query/user/useDeleteMemberMutation.ts
- 쿼리키 수정사항 있는지 살펴보았습니다. 
- 쿼리에서 toast필요한 곳 추가했습니다.
=> SKRF-279 refactor:  query key, toast 관리

src/pages/ProfilePage/AppliedEvents.tsx, src/pages/ProfilePage/BookmarkedEvents.tsx, src/pages/ProfilePage/ProfilePage.style.ts
- 신청 or 북마크한 행사 없을때 신청한 행사 없습니다 보여주기
=> SKRF-281 feat : 신청 or 북마크한 행사 없을때 신청한 행사 없습니다 보여주기

src/apis/event/getSubmittedForms.ts, src/components/SearchInputForm/SearchInputForm.style.ts, src/components/SubmittedForms/SubmittedForms.style.ts, src/components/SubmittedForms/SubmittedForms.tsx, src/hooks/query/event/useGetSubmittedFormsQuery.ts, src/pages/event/SubmittedFormsPage/SubmittedFormsPage.style.ts, src/pages/event/SubmittedFormsPage/SubmittedFormsPage.tsx, src/types/api/submittedForms.ts
- 제출된 폼 api 수정사항을 반영했습니다.
- 제출된 폼 확인 페이지에 페이지네이션 추가하였습니다.
- 해당 페이지 레이아웃을 구현했습니다. 
- '제출된 폼' 텍스트 스타일을 어떻게 줘야 폼 카테고리 시작 부분에 달라 붙는지 모르겠습니다... 하 우선 그냥 중앙에 뒀습니다.
=> SKRF-290 feat: 제출된 폼 api 수정사항 반영

src/components/Modals/FormDetailModal/FormDetailModal.style.ts, src/components/Modals/FormDetailModal/FormDetailModal.tsx, src/components/SubmittedForms/FormStatus/FormStatus.tsx, src/components/SubmittedForms/SubmittedForm/SubmittedForm.tsx, src/components/SubmittedForms/SubmittedForms.tsx, src/types/forms.ts
- 제출된 폼 클릭 시 상세 정보를 볼 수 있습니다. 
- 제출된 폼에서 제출된 시각을 보여주는 건 어떨까요? 우선 백엔드 담당자분께 말해 놓긴 했습니다. 
- 모달 상단에 다른 폼들과 구별되는 정보를 띄워주고 싶은데, 어떤 게 적합할지 모르겠습니다...
=> SKRF-320 feat: 제출된 폼 클릭 시 제출된 폼 상세 정보 모달 뜸

src/components/InviteLink/InviteLink.tsx, src/hooks/query/club/useInviteLinkQuery.ts, src/hooks/query/club/useJoinClub.ts
- 클럽 가입 시 에러 상황에 따라 토스트 메시지가 다르게 출력됩니다. 
- axiosError핸들링을 쿼리에서 하는 게 맞는지 궁금합니다!
=> SKRF-317 refactor: 클럽 가입 시 에러 상황에 따른 토스트 메시지 출력

src/components/Schedule/Schedule.style.ts, src/components/Schedule/Schedule.tsx, src/components/Schedules/Schedules.tsx, src/components/SubmittedForms/SubmittedForm/SubmittedForm.tsx, src/components/SubmittedForms/SubmittedForms.tsx, src/types/event.ts, src/types/forms.ts
- 클럽 행사 조회 Authorization 헤더 추가: 이미 추가하여 데이터 요청하고 있었음. 
- 클럽 일정 확인 responseBody에서 profileImageUrl제거
- 신청된 폼 확인하기 - responseBody의 userForms의 id -> userId로 변경
=> SKRF-324 fix: api 명세 변경사항 반영

src/apis/event/deleteEvent.ts, src/constants/modalMessage.ts, src/hooks/query/event/useDeleteEventMutation.ts, src/pages/event/EventDetailPage/EventDetailPage.tsx
- 작업 내용 1: 이벤트 삭제 기능과 API테스트를 마쳤습니다.
- 없습니다.
=> SKRF-296 feat: 이벤트 삭제 기능 구현

src/apis/users/patchUserInfo.ts, src/components/Profile/Profile.style.ts, src/components/Profile/Profile.tsx, src/components/SideBarMyProfile/SideBarMyProfile.style.ts, src/components/SideBarMyProfile/SideBarMyProfile.tsx, src/components/common/InputForm/InputForm.style.ts, src/components/common/InputForm/InputForm.tsx, src/constants/api.ts, src/hooks/query/user/usePatchUserImageMutation.ts, src/hooks/query/user/usePatchUserInfoMutation.ts, src/hooks/query/user/useUserImageQuery.ts, src/types/api/patchUserInfo.ts
- InputForm 공통 컴포넌트에 editable 속성 추가
- 유저 정보 수정 버튼 추가
- 이미지 수정 invalid 쿼리 키 추가 (사이드 바 프로필 이미지)
- 사이드 바 프로필 스타일 수정
작업하면서 이미지 수정 관련 에러도 조금 잡았어요
=> SKRF-292 feat : 유저 정보 수정 기능

src/components/Profile/Profile.tsx, src/components/common/InputForm/InputForm.tsx
=> SKRF-325 fix : editable 속성 제거

src/components/common/EventCard/EventCard.tsx
=> SKRF-327 fix : navigate주소 수정

src/apis/users/postLogout.ts, src/components/Profile/Profile.style.ts, src/components/Profile/Profile.tsx, src/constants/api.ts, src/constants/modalMessage.ts, src/hooks/query/user/usePostLogoutMutation.ts
- 로그아웃 버튼 추가
- 로그아웃 confirm 모달 추가
- 로그아웃 api 추가
- 로그아웃 시 로컬 스토리지에 있는 토큰 삭제
- 로그아웃 시 메인페이지로 navigate
=> SKRF-294 feat 로그아웃 기능

src/apis/club/deleteClub.ts, src/constants/api.ts, src/constants/modalMessage.ts, src/hooks/query/club/useDeleteClubMutation.ts, src/pages/club/ManageClubPage/ManageClubPage.style.ts, src/pages/club/ManageClubPage/ManageClubPage.tsx, src/routes/router.tsx
- 작업 내용 1: 클럽 삭제 기능 구현 및 API 테스트를 마쳤습니다.
- 클럽 삭제 버튼에 hover시에 효과를 반전시켰는데, 괜찮나요?
=> SKRF-301 feat: 클럽 삭제 기능 구현

src/components/common/Avatar/Avatar.style.ts, src/components/common/Avatar/Avatar.tsx
- 아바타 아이콘도 바꾸고 싶었는데 아이콘 영역이 아이콘 자체의 크기보다 커서 어떻게 맞춰야할지 모르겠네요.
- 편집버튼은 바꿨습니다. 이전보단 낫다고 생각합니다.
=> SKRF-304 design: 아바타 편집버튼 스타일 변경

src/components/ClubMember/ClubMember.style.ts, src/components/ClubMember/ClubMember.tsx, src/components/MemberManager/MemberManager.tsx, src/hooks/query/club/useClubMembersQuery.ts, src/types/user.ts
- API스펙과 속성명이 달라서 멤버 이미지 보이지 않던 오류 수정
- 멤버 레이아웃 정렬 방식 수정
=> SKRF-329 fix : 클럽 멤버 API 속성 오류 수정

src/apis/form/patchSubmittedFormStatus.ts, src/components/ApplyCancelButton/ApplyCancelButton.style.ts, src/components/ApplyCancelButton/ApplyCancelButton.tsx, src/components/SubmittedForms/FormStatus/FormStatus.tsx, src/components/SubmittedForms/SubmittedForm/SubmittedForm.tsx, src/components/SubmittedForms/SubmittedForms.style.ts, src/components/SubmittedForms/SubmittedForms.tsx, src/constants/api.ts, src/constants/form.ts, src/constants/modalMessage.ts, src/hooks/query/form/useSubmittedFormStatusMutation.ts, src/pages/event/SubmittedFormsPage/SubmittedFormsPage.style.ts, src/types/api/patchSubmittedFormStatus.ts
- 제출된 폼의 상태를 변경할 수 있습니다. api 테스트 완료
- '취소하기'를 누르면 더 이상 해당 폼에 대한 상태 변경을 할 수 없습니다. 
- 윈도우 스크린 녹화 이슈로 인해 핸드폰으로 찍은 점 양해 부탁드립니다... :)
=> SKRF-297 feat: 제출된 폼 상태 변경하기 구현

src/components/ClubNotices/ClubNotices.style.ts, src/components/ClubNotices/ClubNotices.tsx, src/components/Modals/NoticeModal.tsx, src/hooks/query/club/useMemberAuth.ts, src/pages/club/ClubHomePage/ClubHomePage.tsx, src/types/api/memberAuth.ts
- MANAGER만 공지사항 추가 버튼이 보이게 만들었습니다
- 공지사항이 없을때 스타일을 추가했습니다
- 공지사항 내용 없을때의 validation을 추가했습니다
=> SKRF-276 feat 공지사항 추가 버튼 권한 설정

src/apis/form/patchSubmittedFormStatus.ts, src/components/ApplyCancelButton/ApplyCancelButton.tsx, src/components/SubmittedForms/FormStatus/FormStatus.tsx, src/components/SubmittedForms/SubmittedForm/SubmittedForm.tsx, src/components/SubmittedForms/SubmittedForms.tsx, src/constants/api.ts, src/hooks/query/event/useCancelEventMutation.ts, src/types/api/cancelEvent.ts, src/types/api/patchSubmittedFormStatus.ts, src/types/forms.ts
[API Endpoint 변경 사항]
applications -> submit
- 신청된 폼 조회 
- 신청 상태 변경 
[ResponseBody 변경]
- 행사의 신청된 폼 조회 (applicationStatus -> participationStatus) 
- 행사의 신청 상태 변경 (status-> participationStatus)
=> SKRF-345 refactor: 신청된 폼 api 수정사항 반영

src/constants/api.ts
=> SKRF-350 fix: 초대한 클럽 정보 api endpoint 수정

src/constants/api.ts
- 작업 내용 1: 행사 신청 API를 명세서에 맞게 변경했습니다.
- 없습니다.
- 없습니다.
=> SKRF-348 fix: 행사 신청 api 변경

src/apis/users/getMyClub.ts, src/components/common/Breadcrumb/Breadcrumb.tsx, src/context/BreadcrumbContext.tsx, src/hooks/useBreadcrumbContext.ts, src/pages/Layout/SideNav.style.ts, src/pages/Layout/SideNav.tsx, src/styles/common.ts, src/types/api/getClub.ts
- 클럽 hover 시 클럽명이 표시됩니다. 
- 하는 김에 클럽 조회 api 타입분리도 했습니다. 
+) pointer 설정 했습니다.
=> SKRF-303 design: 내 클럽 hover 시 클럽명 표시

src/pages/Layout/SideNav.tsx
=> hotfix: 클럽 이동 안 되는 문제 해결

src/constants/api.ts
=> hotfix: 제출된 폼 api endpoint 변경

src/constants/api.ts
- 작업 내용 1: 북마크 api path를 변경했습니다.
- 없습니다.
- 현재 더미데이터 상에서 북마크가 된 상태로 되어있어서, 오류가 뜨는데 더미데이터만 없어지면 작동이 작 됩니다!!
=> SKRF-333 fix: 북마크 api 변경

src/components/FormItem/FormItem.tsx, src/pages/event/SubmitFormPage/SubmitFormPage.tsx
- 작업 내용 1: 폼 item 인덱스를 수정했습니다.
- 없습니다.
- 없습니다.
=> SKRF-352 fix: 폼 아이템 인덱스 수정

src/components/SearchInputForm/SearchInputForm.tsx, src/hooks/useDebounce.ts
- 디바운스 시간 줄였습니다.
- 엔터키 치면 입력된 keyword 그대로 검색됩니다.
=> SKRF-358 refactor: 디바운스 시간 1000->300, 엔터 누르면 해당 keyword 바로 검색

src/hooks/query/club/useClubEventsQuery.ts, src/hooks/query/event/useAllEventsQuery.ts, src/pages/Layout/SideNav.style.ts, src/pages/Layout/SideNav.tsx, src/pages/club/ClubEventPage/ClubEventPage.style.ts, src/pages/club/ClubEventPage/ClubEventPage.tsx, src/pages/club/CreateClubPage/CreateClubPage.style.ts, src/pages/club/CreateClubPage/CreateClubPage.tsx, src/types/components.ts
- 사이드바에서 알림 아이콘 삭제
- 사이드바에서 클럽 생성 버튼 디자인 및 위치 변경
- 클럽 행사 없을 시 안내문구 출력
- 페이지네이션 오류 수정
- 클럽 생성 페이지 레이아웃 수정
=> SKRF-354 design: 사이드바, 클럽 생성 레이아웃 변경

src/constants/api.ts
=> SKRF-368 rename : profile api 엔드포인트

src/components/InviteClubInfo/InviteClubInfo.tsx, src/constants/exceptionCode.ts, src/hooks/query/club/useGetInviteClubInfoQuery.ts, src/hooks/query/club/useJoinClub.ts, src/pages/Layout/SideNav.tsx
- 예외코드를 상수로 만들어 놓았습니다.
- 이렇게 하는 게 옳을지 모르겠어서 클럽 가입 시에만 예외코드에 따라 오류 토스트 메시지 띄우도록 했는데, 어떤가요? 피드백 받습니다. 
- 혜성님이 이전 pr에서 error 상수 파일을 만드셨더라고요?
=> SKRF-346 feat: 예외코드 상수 파일 생성 및 클럽 가입 시 오류 메시지 띄우기

src/components/ClubSetting/ClubSetting.tsx, src/utils/validate.ts
- [ref => state로 변경](https://github.com/Space-Club/Frontend/commit/0830fd71228c2b569932cf68e69f26b67669a84f)
- [클럽 이름, 소개 validate에 trim추가](https://github.com/Space-Club/Frontend/commit/eae8bed50026188c174c094220bcb849f9a75e93)
trim()한 뒤 2줄에서 25줄 판단
=> SKRF-367 refactor : 클럽 이름, 소개 validate 추가

src/components/SearchInputForm/SearchInputForm.tsx, src/components/SearchResult/SearchResult.tsx, src/components/common/EventCard/EventCard.tsx, src/components/common/Poster/Poster.style.ts, src/components/common/Poster/Poster.tsx, src/pages/MainPage/MainPage.tsx, src/pages/SearchResultPage/SearchResultPage.tsx, src/pages/club/ClubEventPage/ClubEventPage.tsx, src/types/api/allEvents.ts, src/types/api/getClubEvents.ts, src/types/api/searchResult.ts, src/types/club.ts, src/types/event.ts
- 행사조회 api 변경사항 반영했습니다. 
- 클럽 일정은 더 변경할 부분이 많아서 다음 브랜치에서 진행하도록 하겠습니다. 
- 현재 events 최초 로드 시 에러가 나는데 이유를 모르겠습니다...! 
AxiosError {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE',
code: "The given id must not be null"
exceptionName: "InvalidDataAccessApiUsageException"
=> SKRF-376 fix: 행사조회 api 변경사항 반영 빠른확인부탁드립니다!

src/components/ClubMember/ClubMember.style.ts, src/components/ClubMember/ClubMember.tsx, src/components/FormInformationEditor/FormInformationEditor.style.ts, src/components/FormInformationEditor/FormInformationEditor.tsx, src/constants/modalMessage.ts
- 멤버 hover시 유저 이름 표기
- 폼 정보 입력 텍스트 value => placeholder로 변경
- 관리모드 설명 수정
=> SKRF-363 fix : 폼 수정 페이지

src/hooks/query/event/useAllEventsQuery.ts, src/hooks/query/event/useGetSubmittedFormsQuery.ts, src/pages/MainPage/MainPage.tsx, src/pages/club/ClubEventPage/ClubEventPage.tsx, src/pages/event/SubmittedFormsPage/SubmittedFormsPage.tsx
- suspense에러 이유를 알아냈습니다!
- 문제가 되는 부분의 suspense처리를 삭제했습니다.
- 다음 브랜치에서 메인페이지와 클럽 행사 페이지, 검색 결과 페이지의 컴포넌트를 분리하고 suspense처리를 해줄 생각입니다!
=> SKRF-378 fix: suspense error

src/components/common/Avatar/Avatar.tsx, src/components/common/TextAreaForm/TextAreaForm.tsx, src/pages/club/CreateClubPage/CreateClubPage.style.ts, src/pages/club/CreateClubPage/CreateClubPage.tsx, src/types/club.ts
- 이미지 인풋 버튼 → 아바타 isEdit 으로 변경하기
- 이미지 첨부 문제 확인하기
- 이미지 jpg,png, jpeg, heic 로 제한하기
- 컴포넌트 위치 중앙으로 이동시키기
- 클럽 소개 input 줄바꿈 안 되게 처리
- 클럽 소개 빈값, trim 처리
=> SKRF-387 fix: create club page

src/hooks/useCarousel.ts
- fix : 공지사항 삭제 시 현재 인덱스 업데이트
마지막 인덱스 삭제 시 인덱스 깨지는 오류 수정했어요
=> SKRF-406 fix : 공지사항 삭제 시 현재 인덱스 업데이트

src/components/UserApplyButton/UserApplyButton.tsx, src/components/common/BookMark/BookMark.tsx, src/hooks/query/event/useDeleteEventMutation.ts, src/hooks/query/event/useEventDetailQuery.ts, src/hooks/query/event/useIsBookmarkQuery.ts, src/hooks/query/event/useIsBookmarkedQuery.ts, src/hooks/query/event/usePatchBookmarkMutation.ts, src/hooks/query/event/usePostEventApplyMutation.ts, src/pages/event/EventDetailPage/EventDetailPage.style.ts, src/pages/event/EventDetailPage/EventDetailPage.tsx, src/types/api/getEventDetail.ts
- 작업 내용 1: 북마크 오류를 수정했습니다.
- 작업 내용 2: 행사 상세페이지에서 invaildQuery를 적용하지 못한 부분들을 적용했습니다.
- 없습니다.
- 아직 행사 신청 여부에 대한 API가 반영되지 않아 이를 제외하고 반영했습니다.
=> SKRF-418 fix: 이벤트 상세페이지 QA

src/components/common/Pagination/Pagination.tsx, src/pages/MainPage/MainPage.tsx, src/pages/ProfilePage/AppliedEvents.tsx, src/pages/ProfilePage/BookmarkedEvents.tsx, src/pages/SearchResultPage/SearchResultPage.tsx, src/pages/club/ClubEventPage/ClubEventPage.tsx, src/pages/event/SubmittedFormsPage/SubmittedFormsPage.tsx
- 페이지네이션 오류 수정: 페이지네이션 컴포넌트에서 선택된 페이지 색깔이 반영되지 않는 문제를 해결했습니다.
- 하는 김에 검색결과 없을 때 보여주는 메시지 style도 common style 적용해주었습니다.
=> SKRF-385 fix: pagination error

src/components/ScheduleCalendar/ScheduleCalendar.tsx
clubhome page pr에다가 수정할걸 그랬네요...머쓱
=> SKRF-420 design: 캘린더 시작 요일 일요일로 변경

src/pages/club/ClubEventPage/ClubEventPage.tsx
- 멤버 권한에 따라 행사 생성하기 버튼이 빛났다 사라져
빛이 나진 않고요 그냥 보이거나 안 보입니다.
=> SKRF-422 refactor: 멤버권한에 따라 행사 생성하기 버튼 접근 제한

src/apis/users/deleteProfileImage.ts, src/components/Profile/Profile.style.ts, src/components/Profile/Profile.tsx, src/components/ProfileImageDeleteButton/ProfileImageDeleteButton.style.ts, src/components/ProfileImageDeleteButton/ProfileImageDeleteButton.tsx, src/constants/api.ts, src/hooks/query/user/useDeleteProfileImage.ts, src/pages/ProfilePage/AppliedEvents.tsx, src/pages/ProfilePage/BookmarkedEvents.style.ts, src/pages/ProfilePage/BookmarkedEvents.tsx, src/pages/ProfilePage/ProfilePage.style.ts
- 기본 이미지로 변경하는 기능 (프로필 이미지 삭제)을 추가했습니다
- 프로필 페이지 레이아웃도 조금 손봤어요
버튼 위치를 옮겨봤는데 괜찮나요?
=> SKRF-421 feat : 기본 이미지로 변경 기능 추가

src/pages/club/ClubEventPage/ClubEventPage.style.ts
- 클럽 행사 페이지에서 행사들을 가운데 정렬했습니다. 
전
후
아놔 페이지네이션 자꾸 올라오네요...
=> SKRF-430 design: 클럽 행사 가운데 정렬

src/components/ManagerButton/ManagerButton.tsx, src/components/UserApplyButton/UserApplyButton.tsx, src/constants/event.ts, src/pages/event/EventDetailPage/CategoryDetail/CategoryDetailForm.tsx, src/pages/event/EventDetailPage/CategoryDetail/ClubDetail.tsx, src/pages/event/EventDetailPage/CategoryDetail/PromotionDetail.tsx, src/pages/event/EventDetailPage/CategoryDetail/RecruitmentDetail.tsx, src/pages/event/EventDetailPage/CategoryDetail/ShowDetail.tsx
- 작업 내용 1: constant/event 에 상수들을 모두 대문자화했습니다.
- 없습니다.
- 아래의 파일들은 모두 어딘가에 종속되어 있어서 건드리지 못했는데, 건드려야 할 부분들이 있을까요? 사실상 event.ts밖에 못 건드렸네요
- events.ts: APPLIED_EVENTS_TAGS
- forms.ts: FormOption으로 설정되어 있는 것들
- storageKey.ts: STORAGE_KEYS
- tab.ts: MAIN_TABS, PROFILE_TABS, CLUB_MEMBER_TABS, CLUB_MANAGER_TABS
- toast.ts: TOAST_COLOR
- user.ts: MEMBER_ROLE_DROPDOWN_OPTIONS
=> SKRF-425 refactor: 상수 대문자화

src/components/FormItem/FormItem.tsx, src/pages/event/SubmitFormPage/SubmitFormPage.style.ts, src/pages/event/SubmitFormPage/SubmitFormPage.tsx
- 작업 내용 1: 제출 버튼 cursor: pointer 적용
- 작업 내용 2: 답변 공백일 경우에 대한 예외처리 적용
- 작업 내용 3: input 1000자 까지 제한
- 없습니다.
- 없습니다.
=> SKRF-419 fix: 신청 폼 페이지 validate 적용

src/components/ScheduleCalendar/ScheduleCalendar.style.ts
- 클럽 달력 이웃달 색상 변경 및 6주일 때 뷰 깨지던 문제 해결했습니다.
=> SKRF-436 design: 클럽 달력 이웃달 색상 변경 및 6주일 때 뷰 깨지던 문제 해결

src/apis/event/postApplyEvent.ts
- 작업 내용 1: ticketCount 버그를 수정했습니다.
- 없습니다.
- 없습니다.
=> ticketCount 버그 수정

src/components/BookmarkedCard/BookmarkedCard.style.ts, src/components/BookmarkedCard/BookmarkedCard.tsx, src/components/common/AppliedEventCard/AppliedEventCard.style.ts, src/components/common/AppliedEventCard/AppliedEventCard.tsx, src/components/common/AppliedEventInfo/AppliedEventInfo.tsx
- 북마크 행사 카드 navigate 추가
- 내가 신청한 행사 navigate 영역 변
=> SKRf-443 fix : 북마크 행사 카드 navigate 추가

src/apis/event/getEventDetail.ts, src/apis/interceptor.ts
- 행사 상세 페이지 진입할 때 로그인 권한으로 api요청하던 오류를 수정했습니다
=> SKRF-456 fix : 행사 상세 비로그인 권한으로 요청

src/components/DeleteMemberButton/DeleteMemberButton.tsx, src/hooks/query/club/useDeleteClubMutation.ts, src/hooks/query/club/useDeleteMemberMutation.ts
- 클럽 추방, 삭제 시 사이드바 쿼리 invalid했습니다
클럽 추방 당했을때 해당 유저 상태 실시간 업데이트는 서버에 틱 설정해서 계속 요청 보내는게 아닌 한 힘들 듯..?
=> SKRF-457 feat : 클럽 추방, 삭제 시 사이드바 쿼리 invalid

src/components/common/Avatar/Avatar.tsx, src/hooks/query/club/useClub.ts
- 혜성님이 만들어 놓으신 예외코드에 따른 토스트 메시지 훅이 있길래 사용했습니다!!!!!!!!!!!!!!!!!!완전 짱!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- 클럽 생성 시 비속어를 작성하고 제출하면 에러 토스트 메시지가 뜹니다.
- 클럽 생성 시 지원하지 않는 이미지 형식을 첨부하거나 파일 크기가 크면 에러 토스트 메시지가 뜹니다.  
킹갓제네럴어쩌구 외쳐 갓혜성 🙇‍♂️🙇‍♂️🙇‍♂️감사합니다!
=> SKRF-450 refactor: 클럽 생성 시 비속어, 이미지파일 예외처리, 예외코드에 따른 토스트 메시지

src/components/InviteClubInfo/InviteClubInfo.tsx, src/hooks/query/club/useGetInviteClubInfoQuery.ts, src/hooks/query/club/useJoinClub.ts, src/pages/club/InvitePage/InvitePage.tsx
- 클럽 가입 시 예외코드에 따른 토스트 메시지를 띄워줍니다.
- 클럽 가입 시 클럽이 유효하지 않을 경우 메시지를 띄워줍니다.
=> SKRF-451 refactor: invite club page exception

src/components/PromotionForm/PromotionForm.tsx, src/components/RecruitForm/RecruitForm.tsx, src/components/common/BookMark/BookMark.tsx, src/constants/modalMessage.ts, src/pages/event/EventDetailPage/CategoryDetail/ClubDetail.tsx, src/pages/event/EventDetailPage/CategoryDetail/PromotionDetail.tsx, src/pages/event/EventDetailPage/CategoryDetail/RecruitmentDetail.tsx, src/pages/event/EventDetailPage/CategoryDetail/ShowDetail.tsx, src/pages/event/EventDetailPage/EventDetailPage.style.ts, src/pages/event/EventDetailPage/EventDetailPage.tsx, src/types/api/getEventDetail.ts
- 작업 내용 1: 북마크 신청시 오류나는 문제 해결
- 작업 내용 2: 행사 상세페이지 반응형 구현
- 작업 내용 3: 행사 상세페이지 내용 부분 padding및 textarea변환
- 작업 내용 4: 행사 상세페이지 홍보부분 장소 나타내지 않는 오류 해결
- 작업 내용 5: 행사 상세페이지 참여신청 min-width조절 및 메시지 텍스트 변경
- 작업 내용 6: 행사 상세페이지 비용이 0일 경우에 대한 예외처리
- 없습니다.
- 비용의 최저값이 아직 정해지지 않아 그 부분은 추가 변경 및 테스트가 필요합니다.
=> SKRF-448 fix: 이벤트 상세페이지 2차 QA

src/apis/event/getAllEvents.ts, src/components/MainEvents.tsx, src/constants/api.ts, src/hooks/query/event/useAllEventsQuery.ts, src/types/api/allEvents.ts, src/types/club.ts
- 마감 기한 지난 행사들이 앞에 정렬되는 거 백엔드에서 해결해서 api변경사항 반영했습니다.
- 아직 백엔드측 변경사항은 pr에만 올라와 있다네요!
=> SKRF-435 fix: 전체행사 조회 api변경 반영

src/components/SearchInputForm/SearchInputForm.tsx, src/pages/SearchResultPage/SearchResultPage.style.ts
- 검색어 입력 후 엔터 누를 때 debouncedKeyword를 keyword로 넘겨줍니다.
- 검색결과가 페이지를 채우면 페이지네이션 하단 여백이 없던 문제를 해결했습니다.
=> SKRF-454 refactor: search page keyword

src/components/UserApplyButton/UserApplyButton.tsx, src/constants/event.ts, src/pages/event/EventDetailPage/EventDetailPage.style.ts, src/pages/event/EventDetailPage/EventDetailPage.tsx
- 작업 내용 1: 신청 기간이 아닐 경우 신청이 되는 에러를 고쳤습니다.
- 없습니다.
=> SKRF-464 fix: 신청이 아닐 경우에 대한 예외처리

src/components/ClubNotice/ClubNotice.style.ts, src/components/Modals/NoticeModal.tsx, src/hooks/query/club/useDeleteClubNoticeMutation.ts, src/hooks/query/club/usePatchClubNoticeMutation.ts, src/hooks/query/club/usePostClubNoticeMutation.ts
- 비속어 예외 처리
- 5번째 줄부터 ...처리
- 모달 닫는 기능 훅에 onSuccess로 옮김 (기존에 실패해도 모달이 닫혔음)
=> SKRF-460 fix : 클럽 공지사항 QA적용

src/hooks/query/club/useClubs.tsx, src/hooks/query/user/useMyProfile.ts
- 비로그인 시 profile api 요청을 하지 않습니다.
=> SKRF-462 fix: 비로그인 시 profile 요청 x

src/constants/tab.ts, src/utils/getBreadcrumb.ts, src/utils/transInviteLink.ts
=> SKRF-467 fix: tab text 행사->홍보로 변경, 초대링크 생성 api response 변경사항 반영

src/constants/api.ts
- 메인페이지 모든 행사 조회 api endpoint를 수정했습니다
=> fix: all events endpoint 변경

src/components/LoginButton/LoginButton.style.ts, src/components/SideBarMyProfile/SideBarMyProfile.style.ts, src/components/SideBarMyProfile/SideBarMyProfile.tsx, src/pages/Layout/Layout.style.ts, src/pages/Layout/Layout.tsx, src/pages/Layout/SideNav.style.ts, src/pages/Layout/SideNav.tsx, src/styles/Theme.ts
- 사이드 바 여닫는 기능
- 사이드 바 스타일 변경
- 사이드 바 로고 추가 ( 클릭시 홈 navigate )
괜찮나요?
=> SKRF-471 refactor : 사이드바 스타일 변경

src/components/common/EventCard/EventCard.style.ts, src/components/common/EventCard/EventCard.tsx
- 이벤트 카드 장소에 common 스타일 적용하였습니다.
before
after
=> design: 이벤트 카드 장소에 common 스타일 적용

src/pages/event/EventDetailPage/CategoryDetail/ClubDetail.tsx, src/pages/event/SubmitFormPage/SubmitFormPage.style.ts
- 작업 내용 1: 행사 상세페이지에 클럽일정의 경우 cost가 toLocaleStrign가 적용되어 있지 않아 적용했습니다.
- 작업 내용 2: 신청 제출 폼 페이지에서 레이아웃이 이상하여 수정했습니다.
- 없습니다.
- 없습니다.
=> SKRF-476 fix: cost toLacaleString 및 신청 제출 폼 레이아웃 변경

src/apis/interceptor.ts
=> SKRF-482 fix : RefreshToken 헤더 분리

src/components/SubmittedForms/Category/Category.style.ts, src/components/SubmittedForms/SubmittedForm/SubmittedForm.style.ts, src/pages/event/EventDetailPage/CategoryDetail/ClubDetail.tsx, src/pages/event/SubmitFormPage/SubmitFormPage.style.ts
- 작업 내용 1: 제출된 폼 페이지 item 가운데 정렬했습니다.
- 브랜치를 파는 것을 깜빡했네요😅
=> SKRF-476 fix: 제출된 폼 페이지 item 가운데 정렬

src/components/common/EventCard/EventCard.style.ts, src/components/common/EventCard/EventCard.tsx, src/styles/common.ts
eventCard 컴포넌트에 common style을 적용했습니다.
=> SKRF-475 design: event card common style적용

src/components/ClubPost/ClubPost.tsx, src/pages/club/ClubPostWritePage/ClubPostWritePage.style.ts, src/pages/club/ClubPostWritePage/ClubPostWritePage.tsx
=> SKRR-11 design: 클럽 게시글 작성 페이지 디자인 구현

src/apis/club/getClub.ts, src/apis/club/getClubPost.ts, src/components/ClubPostDetail/ClubPostDetail.style.ts, src/components/ClubPostDetail/ClubPostDetail.tsx, src/constants/api.ts, src/hooks/query/club/useGetClubPostDetail.ts, src/pages/club/ClubBoardPage/ClubBoardPage.tsx, src/pages/club/ClubPostDetailPage/ClubPostDetailPage.style.ts, src/pages/club/ClubPostDetailPage/ClubPostDetailPage.tsx, src/routes/router.tsx, src/types/api/getClubPost.ts
- 클럽 게시물 상세 조회를 구현했습니다. 
- 댓글은 다음 pr에 반영하겠습니다.
=> SKRR-12 feat: 클럽 게시물 상세조회 구현

src/components/common/MainBanner/MainBanner.style.ts, src/components/common/MainBanner/MainBanner.tsx, src/pages/ProfilePage/ProfilePage.style.ts
- 메인 배너가 빈 배열일 때도 emptyBanner를 보여주게 수정했습니다.
삼항 연산자를 쓰니까 가독성이 많이 떨어지는 것 같아요
```ts
{mainBannerEvents?.length ? (
```
length가 있는지 판단을 mainBannerEvents?.length ? 이렇게 하니까
이것도 가독성이 떨어지는 것 같고...
더 좋은 방법 있을까요?
=> fix : length 0인 경우도 empty 보여주기
